from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.utils import get_column_letter
import logging
from typing import Dict, Any
from datetime import datetime

logger = logging.getLogger(__name__)

class ExcelGenerator:
    def __init__(self):
        self.wb = None
    
    def generate_model(self, job_id: str, data: Dict[str, Any]) -> str:
        """
        Generate complete Excel financial model
        Returns path to the generated file
        """
        try:
            self.wb = Workbook()
            
            # Remove default sheet
            if 'Sheet' in self.wb.sheetnames:
                self.wb.remove(self.wb['Sheet'])
            
            ticker = data.get('company_metadata', {}).get('ticker', 'UNKNOWN')
            company_name = data.get('company_metadata', {}).get('full_name', 'Unknown Company')
            
            # Create all sheets
            self._create_cover_sheet(company_name, ticker, data)
            self._create_pnl_sheet(data)
            self._create_balance_sheet(data)
            self._create_assumptions_sheet(data)
            self._create_advances_mix_sheet(data)
            self._create_advances_build_sheet(data)
            self._create_deposit_schedule_sheet(data)
            self._create_ndtl_sheet(data)
            self._create_gnpa_schedule_sheet(data)
            self._create_roe_tree_sheet(data)
            self._create_regulatory_ratios_sheet(data)
            self._create_valuation_sheet(data)
            self._create_football_field_sheet(data)
            self._create_beta_sheet(data)
            self._create_peer_comps_sheet(data)
            self._create_thesis_sheet(data)
            
            # Save file
            filename = f"{ticker}_model_{datetime.now().strftime('%Y%m%d')}.xlsx"
            filepath = f"/app/generated_models/{filename}"
            self.wb.save(filepath)
            
            logger.info(f"Excel model generated: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"Error generating Excel model: {str(e)}")
            raise
    
    def _create_cover_sheet(self, company_name: str, ticker: str, data: Dict[str, Any]):
        """Create cover sheet"""
        ws = self.wb.create_sheet("Cover", 0)
        
        # Title
        ws['A1'] = f"Financial Model - {company_name}"
        ws['A1'].font = Font(size=20, bold=True)
        
        ws['A3'] = f"Ticker: {ticker}"
        ws['A4'] = f"Date Generated: {datetime.now().strftime('%d %B %Y')}"
        ws['A5'] = "Analyst:"
        
        ws['A7'] = "Recommendation:"
        ws['B7'] = data.get('valuation', {}).get('recommendation', 'TBD')
        ws['A8'] = "Target Price:"
        ws['B8'] = data.get('valuation', {}).get('target_price', 0)
        ws['A9'] = "Upside/Downside:"
        ws['B9'] = data.get('valuation', {}).get('upside', '0%')
        
        ws['A11'] = "Thesis Summary:"
        thesis_summary = data.get('thesis', {}).get('summary', 'Model generated by Mosaic AI')
        ws['A12'] = thesis_summary
        ws['A12'].alignment = Alignment(wrap_text=True)
        
        # Set column width
        ws.column_dimensions['A'].width = 80
    
    def _create_pnl_sheet(self, data: Dict[str, Any]):
        """Create P&L sheet"""
        ws = self.wb.create_sheet("PnL")
        
        ws['A1'] = "Profit & Loss Statement (₹ Crores)"
        ws['A1'].font = Font(size=14, bold=True)
        
        # Headers
        years = ['FY21', 'FY22', 'FY23', 'FY24', 'FY25', 'FY26E', 'FY27E', 'FY28E', 'FY29E', 'FY30E']
        ws['A3'] = "Line Item"
        for i, year in enumerate(years, start=2):
            ws.cell(row=3, column=i).value = year
            ws.cell(row=3, column=i).font = Font(bold=True)
        
        # P&L line items
        row = 4
        pnl_items = [
            "INCOME",
            "Interest Earned",
            "  Interest on Advances",
            "  Income on Investments",
            "  Interest on RBI Balances",
            "  Other Interest Income",
            "Other Income",
            "Total Income",
            "",
            "EXPENDITURE",
            "Interest Expended",
            "Operating Expenses",
            "Provisions and Contingencies",
            "  NPA Provisions",
            "  Taxation",
            "  Other Provisions",
            "Total Expenditure",
            "",
            "PAT",
            "Minority Interest",
            "Retained Earnings"
        ]
        
        for item in pnl_items:
            ws.cell(row=row, column=1).value = item
            if item and not item.startswith(" "):
                ws.cell(row=row, column=1).font = Font(bold=True)
            row += 1
        
        ws.column_dimensions['A'].width = 35
    
    def _create_balance_sheet(self, data: Dict[str, Any]):
        """Create Balance Sheet"""
        ws = self.wb.create_sheet("Balance Sheet")
        
        ws['A1'] = "Balance Sheet (₹ Crores)"
        ws['A1'].font = Font(size=14, bold=True)
        
        years = ['FY21', 'FY22', 'FY23', 'FY24', 'FY25', 'FY26E', 'FY27E', 'FY28E', 'FY29E', 'FY30E']
        ws['A3'] = "Line Item"
        for i, year in enumerate(years, start=2):
            ws.cell(row=3, column=i).value = year
            ws.cell(row=3, column=i).font = Font(bold=True)
        
        ws.column_dimensions['A'].width = 35
    
    def _create_assumptions_sheet(self, data: Dict[str, Any]):
        """Create Assumptions sheet"""
        ws = self.wb.create_sheet("Assumptions")
        
        ws['A1'] = "Forecast Assumptions"
        ws['A1'].font = Font(size=14, bold=True)
        
        ws['A3'] = "Assumption Parameter"
        years = ['FY26E', 'FY27E', 'FY28E', 'FY29E', 'FY30E']
        for i, year in enumerate(years, start=2):
            ws.cell(row=3, column=i).value = year
            ws.cell(row=3, column=i).font = Font(bold=True)
        
        ws.column_dimensions['A'].width = 40
    
    def _create_advances_mix_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Advances Mix")
        ws['A1'] = "Advances Mix by Segment (₹ Cr)"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_advances_build_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Advances Build")
        ws['A1'] = "Advances Build (₹ Cr)"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_deposit_schedule_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Deposit Schedule")
        ws['A1'] = "Deposit Schedule (₹ Cr)"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_ndtl_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("NDTL")
        ws['A1'] = "Net Demand and Time Liabilities"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_gnpa_schedule_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("GNPA Schedule")
        ws['A1'] = "GNPA Schedule"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_roe_tree_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("ROE Tree")
        ws['A1'] = "ROE DuPont Decomposition"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_regulatory_ratios_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Regulatory Ratios")
        ws['A1'] = "Regulatory Ratios"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_valuation_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Valuation")
        ws['A1'] = "Valuation"
        ws['A1'].font = Font(size=14, bold=True)
        
        ws['A3'] = "A) RESIDUAL INCOME VALUATION (RIV)"
        ws['A3'].font = Font(size=12, bold=True)
        
        valuation = data.get('valuation', {})
        
        ws['A5'] = "Cost of Equity (Ke)"
        ws['B5'] = valuation.get('cost_of_equity', 0)
        ws['A6'] = "Terminal Growth Rate"
        ws['B6'] = valuation.get('terminal_growth', 0)
        ws['A7'] = "Target Price"
        ws['B7'] = valuation.get('target_price', 0)
        
        ws.column_dimensions['A'].width = 40
    
    def _create_football_field_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Football Field")
        ws['A1'] = "Valuation Football Field"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_beta_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Beta")
        ws['A1'] = "Beta Calculation"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_peer_comps_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Peer Comps")
        ws['A1'] = "Peer Comparison"
        ws['A1'].font = Font(size=14, bold=True)
    
    def _create_thesis_sheet(self, data: Dict[str, Any]):
        ws = self.wb.create_sheet("Thesis")
        ws['A1'] = "Investment Thesis"
        ws['A1'].font = Font(size=16, bold=True)
        
        thesis_text = data.get('thesis', {}).get('full_text', 'Thesis to be generated')
        
        ws['A3'] = thesis_text
        ws['A3'].alignment = Alignment(wrap_text=True, vertical='top')
        
        ws.column_dimensions['A'].width = 100
        ws.row_dimensions[3].height = 500
